project:
  type: website

website:
  title: "Quarto Template"
  favicon: images/exeter.png
  navbar:
    right:
      - icon: github
        text: GitHub
        href: https://github.com/pythonhealthdatascience/quarto-template/
  sidebar:
    - logo: images/exeter.png
      contents:
        - text: Overview
          href: index.qmd
        - pages/1_making_a_change.qmd
        - pages/2_markdown_basics.qmd
        - pages/3_quarto_features.qmd
        - pages/4_images_videos_documents.qmd
        - pages/5_inline_htmls.qmd